title = "ribbity-tests"
site_name = "ribbity test site"
site_url = "https://ribbity-org.github.io/ribbity/"
github_repo = "ribbity-org/ribbity-test-repo"

add_pages = [ "index.md", "examples.md", "labels.md", "a-page.md"]

github_username = 'ctb'

issues_dump = 'ribbity-test.dmp'

site_templates = 'tests/test-files/site-templates.test'

docs_dir = 'output_docs/test-site'
